# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('government_structures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presidency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('url', models.URLField(verbose_name='url')),
                ('government_structure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='government_structures.GovernmentStructure', verbose_name='government structure')),
                ('urls', models.ManyToManyField(to='institutions.InstitutionURL', verbose_name='urls')),
            ],
            options={
                'verbose_name': 'presidency',
                'verbose_name_plural': 'presidencies',
                'permissions': (('view_presidency', 'Can view presidency'),),
            },
        ),
    ]
