# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presidencies', '0002_presidencyurl_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presidencyurl',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
