# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presidencies', '0004_auto_20171107_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presidency',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='presidency',
            name='name_es',
        ),
    ]
