# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presidencies', '0005_auto_20171109_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presidency',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='presidency',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='presidency',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='presidency',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='presidencyurl',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='presidencyurl',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='presidencyurl',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='presidencyurl',
            name='name_es',
        ),
    ]
