# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presidencies', '0006_auto_20171205_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresidencyTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'presidency Translation',
                'db_table': 'presidencies_presidency_translation',
                'managed': True,
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PresidencyURLTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'presidency url Translation',
                'db_table': 'presidencies_presidencyurl_translation',
                'managed': True,
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='presidency',
            name='description',
        ),
        migrations.RemoveField(
            model_name='presidency',
            name='title',
        ),
        migrations.RemoveField(
            model_name='presidencyurl',
            name='description',
        ),
        migrations.RemoveField(
            model_name='presidencyurl',
            name='name',
        ),
        migrations.AddField(
            model_name='presidencyurltranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='presidencies.PresidencyURL'),
        ),
        migrations.AddField(
            model_name='presidencytranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='presidencies.Presidency'),
        ),
        migrations.AlterUniqueTogether(
            name='presidencyurltranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='presidencytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
