# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presidencies', '0007_auto_20171205_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presidencyurl',
            options={'permissions': (('view_presidency_url', 'Can view presidency urls'),), 'verbose_name': 'presidency url', 'verbose_name_plural': 'presidency urls'},
        ),
    ]
