# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 11:49
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('presidencies', '0008_auto_20171226_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presidencytranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='presidencyurltranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='description'),
        ),
    ]
