# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presidencies', '0009_auto_20180221_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presidencyurl',
            options={'ordering': ('order',), 'permissions': (('view_presidency_url', 'Can view presidency urls'),), 'verbose_name': 'presidency url', 'verbose_name_plural': 'presidency urls'},
        ),
        migrations.AddField(
            model_name='presidencyurl',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
