# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presidencies', '0010_auto_20180226_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidency',
            name='boost',
            field=models.FloatField(default=4.0, verbose_name='boost'),
        ),
    ]
