# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociocultural_departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socioculturaldepartment',
            options={'permissions': (('view_socioculturaldepartment', 'Can view Socio Cultural Department'),), 'verbose_name': 'Socio Cultural Department', 'verbose_name_plural': 'Socio Cultural Departments'},
        ),
        migrations.AlterModelOptions(
            name='socioculturaldepartmenttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Socio Cultural Department Translation'},
        ),
        migrations.AlterModelOptions(
            name='socioculturaldepartmenturl',
            options={'ordering': ('order',), 'permissions': (('view_socioculturaldepartment_url', 'Can view Socio Cultural Department url'),), 'verbose_name': 'Socio Cultural Department url', 'verbose_name_plural': 'Socio Cultural Department urls'},
        ),
        migrations.AlterModelOptions(
            name='socioculturaldepartmenturltranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Socio Cultural Department url Translation'},
        ),
    ]
