# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170919_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='font_size',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='font size'),
        ),
    ]
