# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171103_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='font_size',
            field=models.CharField(blank=True, default='16px', max_length=100, verbose_name='font size'),
        ),
    ]
