# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 20:45
from __future__ import unicode_literals

from django.db import migrations


def set_rut_for_users(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model('users', 'User')

    users = User.objects.all()

    for user in users:
        user.rut = user.id
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171219_1700'),
    ]

    operations = [
        migrations.RunPython(set_rut_for_users),
    ]
