# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_set_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(db_index=True, max_length=13, unique=True, verbose_name='rut'),
        ),
    ]
