# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-04 18:06
from __future__ import unicode_literals

import aldryn_categories.fields
import articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import sortedm2m.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aldryn_categories', '0004_auto_20150623_0859'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0017_auto_20180404_1157'),
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publishing date')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='is published')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='is featured')),
                ('is_draft', models.BooleanField(db_index=True, default=True, editable=False)),
                ('categories', aldryn_categories.fields.CategoryManyToManyField(blank=True, related_name='articles', to='aldryn_categories.Category', verbose_name='categories')),
                ('content', articles.models.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', slotname='article_content', to='cms.Placeholder')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('featured_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.FILER_IMAGE_MODEL, verbose_name='featured image')),
                ('public', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='articles.Article')),
                ('related', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='articles.Article', verbose_name='related articles')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ('-publishing_date',),
                'permissions': (('view_article', 'Can view article'),),
            },
        ),
    ]
