# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 19:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djangocms_text_ckeditor.fields
import filer.fields.image
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date this article will be published', verbose_name='publishing_date')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_image', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
            ],
            options={
                'permissions': (('view_article', 'Can view article'),),
                'verbose_name_plural': 'articles',
                'ordering': ('-publishing_date',),
                'verbose_name': 'article',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('content', djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='content')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='articles.Article')),
            ],
            options={
                'db_tablespace': '',
                'db_table': 'articles_article_translation',
                'default_permissions': (),
                'managed': True,
                'verbose_name': 'article Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='articletranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
