# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 22:41
from __future__ import unicode_literals

import articles.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20180515_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=articles.models.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', slotname='article_content', to='cms.Placeholder'),
        ),
    ]
