# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('government_structures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicServant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='phone')),
                ('twitter', models.CharField(max_length=50)),
                ('government_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government_structures.GovernmentStructure', verbose_name='government structure')),
            ],
            options={
                'verbose_name': 'public servant',
                'verbose_name_plural': 'public servants',
                'permissions': (('view_public_servant', 'Can view public_servants'),),
            },
        ),
    ]
