# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_servants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicservant',
            name='charge',
            field=models.CharField(max_length=100, null=True, verbose_name='charge'),
        ),
    ]
