# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('public_servants', '0003_publicservant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicservant',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='publicservant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='publicservant',
            name='twitter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
