# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_servants', '0007_auto_20171205_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicServantTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('charge', models.CharField(max_length=100, null=True, verbose_name='charge')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'public servant Translation',
                'default_permissions': (),
                'db_table': 'public_servants_publicservant_translation',
                'db_tablespace': '',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='publicservant',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='publicservant',
            name='description',
        ),
        migrations.AddField(
            model_name='publicservanttranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='public_servants.PublicServant'),
        ),
        migrations.AlterUniqueTogether(
            name='publicservanttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
