# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_servants', '0008_auto_20171205_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicservant',
            options={'permissions': (('view_public_servant', 'Can view public servants'),), 'verbose_name': 'public servant', 'verbose_name_plural': 'public servants'},
        ),
    ]
