# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 15:40
from __future__ import unicode_literals

import base.models
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public_servants', '0009_auto_20171221_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicservant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='publicservant',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(max_length=255, null=True, upload_to=base.models.file_path, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='publicservanttranslation',
            name='charge',
            field=models.CharField(max_length=255, null=True, verbose_name='charge'),
        ),
    ]
