# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 13:09
from __future__ import unicode_literals

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_servants', '0012_auto_20180221_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicservant',
            name='government_structure',
            field=models.ForeignKey(default=base.models.lastest_government_structure, on_delete=django.db.models.deletion.CASCADE, to='government_structures.GovernmentStructure', verbose_name='government structure'),
        ),
    ]
