# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 13:00
from __future__ import unicode_literals

import base.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public_servants', '0013_auto_20180312_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicservant',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=255, null=True, upload_to=base.models.file_path, verbose_name='photo'),
        ),
    ]
