# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_servants', '0014_auto_20180314_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicservant',
            name='boost',
            field=models.FloatField(default=3.0, verbose_name='boost'),
        ),
    ]
