# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_structures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentstructure',
            name='publication_date',
            field=models.DateTimeField(unique=True, verbose_name='publication date'),
        ),
    ]
