# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('government_structures', '0002_governmentstructure_archive_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governmentstructure',
            options={'ordering': ('-publication_date',), 'permissions': (('view_government_structure', 'Can view government structures'),), 'verbose_name': 'government structure', 'verbose_name_plural': 'government structures'},
        ),
    ]
