# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0002_auto_20171018_1233'),
        ('public_companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publiccompany',
            unique_together=set([('name', 'government')]),
        ),
    ]
