# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20171212_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-analytic_visits',)},
        ),
        migrations.AddField(
            model_name='file',
            name='analytic_visits',
            field=models.PositiveIntegerField(default=0, verbose_name='analytic visits'),
        ),
    ]
