# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0001_initial'),
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='procedures_and_benefits',
            field=models.URLField(blank=True, verbose_name='procedures and benefits'),
        ),
        migrations.AlterUniqueTogether(
            name='ministry',
            unique_together=set([('name', 'government')]),
        ),
    ]
