# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0003_auto_20171025_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='name')),
                ('url', models.URLField(blank=True, verbose_name='url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ministry',
            name='public_enterprises',
        ),
        migrations.AlterField(
            model_name='ministry',
            name='public_servants',
            field=models.ManyToManyField(related_name='ministries', to='public_servants.PublicServant', verbose_name='public servants'),
        ),
        migrations.AddField(
            model_name='publicservice',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministries.Ministry', verbose_name='ministry'),
        ),
    ]
