# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0005_auto_20171025_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicservice',
            options={'ordering': ('name',), 'verbose_name': 'public service', 'verbose_name_plural': 'public services'},
        ),
    ]
