# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0007_auto_20171027_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='description_es',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='slug_en',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='slug_es',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='publicservice',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='publicservice',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
    ]
