# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0008_auto_20171107_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicservice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='publicservice',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='publicservice',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='publicservice',
            unique_together=set([('name', 'ministry')]),
        ),
    ]
