# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0011_auto_20171205_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministrytranslation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
