# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0012_auto_20171206_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicServiceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'db_table': 'ministries_publicservice_translation',
                'default_permissions': (),
                'managed': True,
                'verbose_name': 'public service Translation',
                'db_tablespace': '',
            },
        ),
        migrations.AlterModelOptions(
            name='publicservice',
            options={'ordering': ('importance',), 'verbose_name': 'public service', 'verbose_name_plural': 'public services'},
        ),
        migrations.AddField(
            model_name='publicservice',
            name='importance',
            field=models.PositiveIntegerField(default=0, verbose_name='importance'),
        ),
        migrations.AlterUniqueTogether(
            name='publicservice',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='publicservicetranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='ministries.PublicService'),
        ),
        migrations.RemoveField(
            model_name='publicservice',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='publicservicetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
