# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0016_auto_20180312_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='public_servants',
            field=models.ManyToManyField(blank=True, related_name='ministries', to='public_servants.PublicServant', verbose_name='public servants'),
        ),
    ]
