# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0017_auto_20180314_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='boost',
            field=models.FloatField(default=2.0, verbose_name='boost'),
        ),
        migrations.AddField(
            model_name='publicservice',
            name='boost',
            field=models.FloatField(default=1.5, verbose_name='boost'),
        ),
    ]
