# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government',
            name='publication_date',
            field=models.DateField(unique=True, verbose_name='publication date'),
        ),
    ]
