# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ('name',), 'permissions': (('view_commune', 'Can view communes'),), 'verbose_name': 'commune', 'verbose_name_plural': 'communes'},
        ),
    ]
