# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20171024_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='region',
            name='governor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public_servants.PublicServant', verbose_name='governor'),
        ),
        migrations.AlterField(
            model_name='region',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='region',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
