# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20171027_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='governor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public_servants.PublicServant', verbose_name='governor'),
        ),
    ]
