# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_auto_20171027_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('order',), 'permissions': (('view_region', 'Can view regions'),), 'verbose_name': 'region', 'verbose_name_plural': 'regions'},
        ),
        migrations.AddField(
            model_name='region',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
