# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0008_auto_20171109_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug_en',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='region',
            name='slug_es',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='slug'),
        ),
    ]
