# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0009_auto_20171109_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='municipality_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='commune',
            name='municipality_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
    ]
