# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0014_auto_20180221_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='region',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='phone'),
        ),
    ]
