# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20171130_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'managed': True,
                'verbose_name': 'campaign Translation',
                'db_tablespace': '',
                'db_table': 'campaigns_campaign_translation',
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='title',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='title_es',
        ),
        migrations.AddField(
            model_name='campaigntranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='campaigns.Campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigntranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
