# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20171130_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('is_featured',), 'permissions': (('view_campaign', 'Can view campaign'),), 'verbose_name': 'campaign', 'verbose_name_plural': 'campaigns'},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='featured_since',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='featured_until',
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is featured'),
        ),
    ]
