# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20171204_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='image'),
        ),
    ]
