# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 14:26
from __future__ import unicode_literals

import campaigns.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20171204_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('-is_featured',), 'permissions': (('view_campaign', 'Can view campaign'),), 'verbose_name': 'campaign', 'verbose_name_plural': 'campaigns'},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='is_active',
        ),
        migrations.AddField(
            model_name='campaign',
            name='activation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date this campaign will be activated', verbose_name='activation datetime`'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='deactivation_datetime',
            field=models.DateTimeField(default=campaigns.models.default_end_datetime, help_text='The date this campaign will be deactivated', verbose_name='deactivation datetime`'),
        ),
    ]
