# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20171204_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
