# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20171206_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
    ]
