# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_auto_20171206_1013'),
        ('campaigns', '0009_auto_20171206_1136'),
    ]

    operations = [
    ]
