# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_auto_20171206_1641'),
        ('campaigns', '0010_auto_20171207_0832'),
    ]

    operations = [
    ]
