# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_merge_20171207_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='page',
        ),
        migrations.AddField(
            model_name='campaigntranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='slug'),
        ),
    ]
