# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 14:02
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_auto_20171219_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', slotname='campaign content', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='header_content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_as_header', slotname='campaign header', to='cms.Placeholder'),
        ),
    ]
