# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 12:51
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_auto_20171222_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', slotname='campaign content', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='header_content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_as_header', slotname='campaign header', to='cms.Placeholder'),
        ),
    ]
