# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_auto_20171226_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='importance',
            field=models.PositiveIntegerField(default=0, verbose_name='importance'),
        ),
    ]
