# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_campaign_importance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('-is_featured', 'importance'), 'permissions': (('view_campaign', 'Can view campaign'),), 'verbose_name': 'campaign', 'verbose_name_plural': 'campaigns'},
        ),
    ]
