# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_auto_20180118_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image_crop_when_on_pair',
            field=models.CharField(choices=[('0,0', 'Top left'), (',0', 'Top center'), ('-0,0', 'Top right'), ('0,', 'Middle left'), (',', 'Middle center'), ('-0,', 'Middle right'), ('0,-0', 'Bottom left'), (',-0', 'Bottom center'), ('-0,-0', 'Bottom right')], default=',', help_text='crop orientation for size: 1072x240', max_length=255, verbose_name='image crop when on pair'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image_crop_when_on_trio',
            field=models.CharField(choices=[('0,0', 'Top left'), (',0', 'Top center'), ('-0,0', 'Top right'), ('0,', 'Middle left'), (',', 'Middle center'), ('-0,', 'Middle right'), ('0,-0', 'Bottom left'), (',-0', 'Bottom center'), ('-0,-0', 'Bottom right')], default=',', help_text='crop orientation for size: 700x240', max_length=255, verbose_name='image crop when on trio'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image_crop_when_single',
            field=models.CharField(choices=[('0,0', 'Top left'), (',0', 'Top center'), ('-0,0', 'Top right'), ('0,', 'Middle left'), (',', 'Middle center'), ('-0,', 'Middle right'), ('0,-0', 'Bottom left'), (',-0', 'Bottom center'), ('-0,-0', 'Bottom right')], default=',', help_text='crop orientation for size: 1080x600', max_length=255, verbose_name='image crop when single'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image_crop_when_small',
            field=models.CharField(choices=[('0,0', 'Top left'), (',0', 'Top center'), ('-0,0', 'Top right'), ('0,', 'Middle left'), (',', 'Middle center'), ('-0,', 'Middle right'), ('0,-0', 'Bottom left'), (',-0', 'Bottom center'), ('-0,-0', 'Bottom right')], default=',', help_text='crop orientation for size: 164x90', max_length=255, verbose_name='image crop when small'),
        ),
    ]
