# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_auto_20180125_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='boost',
            field=models.FloatField(default=1.0, verbose_name='boost'),
        ),
    ]
