# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('government_structures', '0001_initial'),
        ('ministries', '0007_auto_20171027_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEnterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('government_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government_structures.GovernmentStructure', verbose_name='government structure')),
                ('ministries', models.ManyToManyField(blank=True, to='ministries.Ministry', verbose_name='ministries')),
            ],
            options={
                'verbose_name': 'public enterprise',
                'verbose_name_plural': 'public enterprises',
                'permissions': (('view_publicenterprise', 'Can view public enterprise'),),
            },
        ),
    ]
