# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicenterprise',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='publicenterprise',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
