# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_enterprises', '0002_auto_20171107_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicenterprise',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='publicenterprise',
            name='name_es',
        ),
    ]
