# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobcl_cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageplugin',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='caption'),
        ),
    ]
