# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20171219_1102'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('gobcl_cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImagePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='gobcl_cms_galleryimageplugin', serialize=False, to='cms.CMSPlugin')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='caption')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GalleryPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='gobcl_cms_galleryplugin', serialize=False, to='cms.CMSPlugin')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='imageplugin',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='imageplugin',
            name='image',
        ),
        migrations.DeleteModel(
            name='ImagePlugin',
        ),
    ]
