# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobcl_cms', '0003_auto_20171226_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimageplugin',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='galleryplugin',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
    ]
