# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gobcl_cms', '0007_articlecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecount',
            name='article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='count', to='aldryn_newsblog.Article', verbose_name='article'),
        ),
    ]
