# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20171226_1915'),
        ('filer', '0007_auto_20161016_1055'),
        ('gobcl_cms', '0010_plaintextplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='gobcl_cms_audioplugin', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('audio_length', models.CharField(max_length=10, verbose_name='audio length')),
                ('audio', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='audio')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
