# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobcl_cms', '0011_audioplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentplugin',
            name='last_elements_on_right_column',
            field=models.PositiveIntegerField(default=0, help_text='move the number of last elements indicated by this field to the right column', verbose_name='move last x elements to right '),
        ),
    ]
