# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 21:12
from __future__ import unicode_literals

from django.db import migrations

from gobcl_cms.utils import create_redirects


class Migration(migrations.Migration):

    dependencies = [
        ('gobcl_cms', '0012_sectionplugin'),
    ]

    operations = [
        migrations.RunPython(create_redirects()),
    ]
