regions_data = [
    {
        'communes': [
            {'name': u'Antofagasta'},
            {'name': u'Calama'},
            {'name': u'María Elena'},
            {'name': u'Mejillones'},
            {'name': u'Ollagüe'},
            {'name': u'San Pedro de Atacama'},
            {'name': u'Sierra Gorda'},
            {'name': u'Taltal'},
            {'name': u'Tocopilla'}
        ],
        'name': u'Región de Antofagasta'
    },
    {
        'communes': [
            {'name': u'Arica'},
            {'name': u'Camarones'},
            {'name': u'General Lagos'},
            {'name': u'Putre'}],
        'name': u'Región de Arica-Parinacota'
    },
    {
        'communes': [
            {'name': u'Alto del Carmen'},
            {'name': u'Caldera'},
            {'name': u'Chañaral'},
            {'name': u'Copiapó'},
            {'name': u'Diego de Almagro'},
            {'name': u'Freirina'},
            {'name': u'Huasco'},
            {'name': u'Tierra Amarilla'},
            {'name': u'Vallenar'}],
        'name': u'Región de Atacama'
    },
    {
        'communes': [
            {'name': u'Aysén'},
            {'name': u'Chile Chico'},
            {'name': u'Cisnes'},
            {'name': u'Cochrane'},
            {'name': u'Coyhaique'},
            {'name': u'Guaitecas'},
            {'name': u'Lago Verde'},
            {'name': u"O'Higgins"},
            {'name': u'Río Ibáñez'},
            {'name': u'Tortel'}],
        'name': u'Región de Aysén del General Carlos Ibáñez del Campo'
    },
    {
        'communes': [
            {'name': u'Andacollo'},
            {'name': u'Canela'},
            {'name': u'Combarbalá'},
            {'name': u'Coquimbo'},
            {'name': u'Illapel'},
            {'name': u'La Higuera'},
            {'name': u'La Serena'},
            {'name': u'Los Vilos'},
            {'name': u'Monte Patria'},
            {'name': u'Ovalle'},
            {'name': u'Paiguano'},
            {'name': u'Punitaqui'},
            {'name': u'Río Hurtado'},
            {'name': u'Salamanca'},
            {'name': u'Vicuña'}
        ],
        'name': u'Región de Coquimbo'
    },
    {
        'communes': [
            {'name': u'Angol'},
            {'name': u'Carahue'},
            {'name': u'Cholchol'},
            {'name': u'Collipulli'},
            {'name': u'Cunco'},
            {'name': u'Curacautín'},
            {'name': u'Curarrehue'},
            {'name': u'Ercilla'},
            {'name': u'Freire'},
            {'name': u'Galvarino'},
            {'name': u'Gorbea'},
            {'name': u'Lautaro'},
            {'name': u'Loncoche'},
            {'name': u'Lonquimay'},
            {'name': u'Los Sauces'},
            {'name': u'Lumaco'},
            {'name': u'Melipeuco'},
            {'name': u'Nueva Imperial'},
            {'name': u'Padre Las Casas'},
            {'name': u'Perquenco'},
            {'name': u'Pitrufquén'},
            {'name': u'Pucón'},
            {'name': u'Purén'},
            {'name': u'Renaico'},
            {'name': u'Saavedra'},
            {'name': u'Temuco'},
            {'name': u'Teodoro Schmidt'},
            {'name': u'Toltén'},
            {'name': u'Traiguén'},
            {'name': u'Victoria'},
            {'name': u'Vilcún'},
            {'name': u'Villarrica'}],
        'name': u'Región de la Araucanía'
    },
    {
        'communes': [
            {'name': u'Alto Biobío'},
            {'name': u'Antuco'},
            {'name': u'Arauco'},
            {'name': u'Bulnes'},
            {'name': u'Cabrero'},
            {'name': u'Cañete'},
            {'name': u'Chiguayante'},
            {'name': u'Chillán'},
            {'name': u'Chillán Viejo'},
            {'name': u'Cobquecura'},
            {'name': u'Coelemu'},
            {'name': u'Coihueco'},
            {'name': u'Concepción'},
            {'name': u'Contulmo'},
            {'name': u'Coronel'},
            {'name': u'Curanilahue'},
            {'name': u'El Carmen'},
            {'name': u'Florida'},
            {'name': u'Hualpén'},
            {'name': u'Hualqui'},
            {'name': u'Laja'},
            {'name': u'Lebu'},
            {'name': u'Los Álamos'},
            {'name': u'Los Ángeles'},
            {'name': u'Lota'},
            {'name': u'Mulchén'},
            {'name': u'Nacimiento'},
            {'name': u'Negrete'},
            {'name': u'Ninhue'},
            {'name': u'Ñiquén'},
            {'name': u'Pemuco'},
            {'name': u'Penco'},
            {'name': u'Pinto'},
            {'name': u'Portezuelo'},
            {'name': u'Quilaco'},
            {'name': u'Quilleco'},
            {'name': u'Quillón'},
            {'name': u'Quirihue'},
            {'name': u'Ránquil'},
            {'name': u'San Carlos'},
            {'name': u'San Fabián'},
            {'name': u'San Ignacio'},
            {'name': u'San Nicolás'},
            {'name': u'San Pedro de La Paz'},
            {'name': u'San Rosendo'},
            {'name': u'Santa Bárbara'},
            {'name': u'Santa Juana'},
            {'name': u'Talcahuano'},
            {'name': u'Tirúa'},
            {'name': u'Tomé'},
            {'name': u'Treguaco'},
            {'name': u'Tucapel'},
            {'name': u'Yumbel'},
            {'name': u'Yungay'}
        ],
        'name': u'Región del Bío Bío'
    },
    {
        'communes': [
            {'name': u'Chépica'},
            {'name': u'Chimbarongo'},
            {'name': u'Codegua'},
            {'name': u'Coinco'},
            {'name': u'Coltauco'},
            {'name': u'Doñihue'},
            {'name': u'Graneros'},
            {'name': u'La Estrella'},
            {'name': u'Las Cabras'},
            {'name': u'Litueche'},
            {'name': u'Lolol'},
            {'name': u'Machalí'},
            {'name': u'Malloa'},
            {'name': u'Marchihue'},
            {'name': u'Mostazal'},
            {'name': u'Nancagua'},
            {'name': u'Navidad'},
            {'name': u'Olivar'},
            {'name': u'Palmilla'},
            {'name': u'Paredones'},
            {'name': u'Peralillo'},
            {'name': u'Peumo'},
            {'name': u'Pichidegua'},
            {'name': u'Pichilemu'},
            {'name': u'Placilla'},
            {'name': u'Pumanque'},
            {'name': u'Quinta de Tilcoco'},
            {'name': u'Rancagua'},
            {'name': u'Rengo'},
            {'name': u'Requínoa'},
            {'name': u'San Fernando'},
            {'name': u'Santa Cruz'},
            {'name': u'San Vicente'}],
        'name': u"Región del Libertador Bernardo O'Higgins"
    },
    {
        'communes': [
            {'name': u'Cauquenes'},
            {'name': u'Chanco'},
            {'name': u'Colbún'},
            {'name': u'Constitución'},
            {'name': u'Curepto'},
            {'name': u'Curicó'},
            {'name': u'Empedrado'},
            {'name': u'Hualañé'},
            {'name': u'Licantén'},
            {'name': u'Linares'},
            {'name': u'Longaví'},
            {'name': u'Maule'},
            {'name': u'Molina'},
            {'name': u'Parral'},
            {'name': u'Pelarco'},
            {'name': u'Pelluhue'},
            {'name': u'Pencahue'},
            {'name': u'Rauco'},
            {'name': u'Retiro'},
            {'name': u'Río Claro'},
            {'name': u'Romeral'},
            {'name': u'Sagrada Familia'},
            {'name': u'San Clemente'},
            {'name': u'San Javier'},
            {'name': u'San Rafael'},
            {'name': u'Talca'},
            {'name': u'Teno'},
            {'name': u'Vichuquén'},
            {'name': u'Villa Alegre'},
            {'name': u'Yerbas Buenas'}],
        'name': u'Región del Maule'
    },
    {
        'communes': [
            {'name': u'Ancud'},
            {'name': u'Calbuco'},
            {'name': u'Castro'},
            {'name': u'Chaitén'},
            {'name': u'Chonchi'},
            {'name': u'Cochamó'},
            {'name': u'Curaco de Vélez'},
            {'name': u'Dalcahue'},
            {'name': u'Fresia'},
            {'name': u'Frutillar'},
            {'name': u'Futaleufú'},
            {'name': u'Hualaihué'},
            {'name': u'Llanquihue'},
            {'name': u'Los Muermos'},
            {'name': u'Maullín'},
            {'name': u'Osorno'},
            {'name': u'Palena'},
            {'name': u'Puerto Montt'},
            {'name': u'Puerto Octay'},
            {'name': u'Puerto Varas'},
            {'name': u'Puqueldón'},
            {'name': u'Purranque'},
            {'name': u'Puyehue'},
            {'name': u'Queilén'},
            {'name': u'Quellón'},
            {'name': u'Quemchi'},
            {'name': u'Quinchao'},
            {'name': u'Río Negro'},
            {'name': u'San Juan de la Costa'},
            {'name': u'San Pablo'}],
        'name': u'Región de los Lagos'
    },
    {
        'communes': [
            {'name': u'Corral'},
            {'name': u'Futrono'},
            {'name': u'Lago Ranco'},
            {'name': u'Lanco'},
            {'name': u'La Unión'},
            {'name': u'Los Lagos'},
            {'name': u'Máfil'},
            {'name': u'Mariquina'},
            {'name': u'Paillaco'},
            {'name': u'Panguipulli'},
            {'name': u'Río Bueno'},
            {'name': u'Valdivia'}],
        'name': u'Región de Los Ríos'
    },
    {
        'communes': [
            {'name': u'Antártica'},
            {'name': u'Cabo de Hornos'},
            {'name': u'Laguna Blanca'},
            {'name': u'Natales'},
            {'name': u'Porvenir'},
            {'name': u'Primavera'},
            {'name': u'Punta Arenas'},
            {'name': u'Río Verde'},
            {'name': u'San Gregorio'},
            {'name': u'Timaukel'},
            {'name': u'Torres del Paine'}],
        'name': u'Región de Magallanes y la Antártica Chilena'
    },
    {
        'communes': [
            {'name': u'Alto Hospicio'},
            {'name': u'Camiña'},
            {'name': u'Colchane'},
            {'name': u'Huara'},
            {'name': u'Iquique'},
            {'name': u'Pica'},
            {'name': u'Pozo Almonte'}],
        'name': u'Región de Tarapacá'
    },
    {
        'communes': [
            {'name': u'Algarrobo'},
            {'name': u'Cabildo'},
            {'name': u'Calera'},
            {'name': u'Calle Larga'},
            {'name': u'Cartagena'},
            {'name': u'Casablanca'},
            {'name': u'Catemu'},
            {'name': u'Concón'},
            {'name': u'El Quisco'},
            {'name': u'El Tabo'},
            {'name': u'Hijuelas'},
            {'name': u'Isla de Pascua'},
            {'name': u'Juan Fernández'},
            {'name': u'La Cruz'},
            {'name': u'La Ligua'},
            {'name': u'Limache'},
            {'name': u'Llaillay'},
            {'name': u'Los Andes'},
            {'name': u'Nogales'},
            {'name': u'Olmué'},
            {'name': u'Panquehue'},
            {'name': u'Papudo'},
            {'name': u'Petorca'},
            {'name': u'Puchuncaví'},
            {'name': u'Putaendo'},
            {'name': u'Quillota'},
            {'name': u'Quilpué'},
            {'name': u'Quintero'},
            {'name': u'Rinconada'},
            {'name': u'San Antonio'},
            {'name': u'San Esteban'},
            {'name': u'San Felipe'},
            {'name': u'Santa María'},
            {'name': u'Santo Domingo'},
            {'name': u'Valparaíso'},
            {'name': u'Villa Alemana'},
            {'name': u'Viña del Mar'},
            {'name': u'Zapallar'}],
        'name': u'Región de Valparaíso'
    },
    {
        'communes': [
            {'name': u'Alhué'},
            {'name': u'Buin'},
            {'name': u'Calera de Tango'},
            {'name': u'Cerrillos'},
            {'name': u'Cerro Navia'},
            {'name': u'Colina'},
            {'name': u'Conchalí'},
            {'name': u'Curacaví'},
            {'name': u'El Bosque'},
            {'name': u'El Monte'},
            {'name': u'Estación Central'},
            {'name': u'Huechuraba'},
            {'name': u'Independencia'},
            {'name': u'Isla de Maipo'},
            {'name': u'La Cisterna'},
            {'name': u'La Florida'},
            {'name': u'La Granja'},
            {'name': u'Lampa'},
            {'name': u'La Pintana'},
            {'name': u'La Reina'},
            {'name': u'Las Condes'},
            {'name': u'Lo Barnechea'},
            {'name': u'Lo Espejo'},
            {'name': u'Lo Prado'},
            {'name': u'Macul'},
            {'name': u'Maipú'},
            {'name': u'María Pinto'},
            {'name': u'Melipilla'},
            {'name': u'Ñuñoa'},
            {'name': u'Padre Hurtado'},
            {'name': u'Paine'},
            {'name': u'Pedro Aguirre Cerda'},
            {'name': u'Peñaflor'},
            {'name': u'Peñalolén'},
            {'name': u'Pirque'},
            {'name': u'Providencia'},
            {'name': u'Pudahuel'},
            {'name': u'Puente Alto'},
            {'name': u'Quilicura'},
            {'name': u'Quinta Normal'},
            {'name': u'Recoleta'},
            {'name': u'Renca'},
            {'name': u'San Bernardo'},
            {'name': u'San Joaquín'},
            {'name': u'San José de Maipo'},
            {'name': u'San Miguel'},
            {'name': u'San Pedro'},
            {'name': u'San Ramón'},
            {'name': u'Santiago'},
            {'name': u'Talagante'},
            {'name': u'Tiltil'},
            {'name': u'Vitacura'}
        ],
        'name': u'Región Metropolitana de Santiago'
    }
]
