# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ('order',), 'permissions': (('view_link', 'Can view link'),), 'verbose_name': 'footer link', 'verbose_name_plural': 'footer links'},
        ),
        migrations.AddField(
            model_name='footerlink',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='oder'),
        ),
    ]
