# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 20:29
from __future__ import unicode_literals

from django.db import migrations


def reorder_footer_links(apps, schema_editor):
    FooterLink = apps.get_model('links', 'FooterLink')
    FooterLink.reorder_order()


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20180306_1513'),
    ]

    operations = [
    ]
