# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20180307_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='order'),
        ),
    ]
