# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('government_structures', '0001_initial'),
        ('public_servants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, verbose_name='slug')),
                ('url', models.URLField(verbose_name='url')),
                ('procedures_and_benefits', models.URLField(blank=True, verbose_name='procedures and benefits')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_servants.PublicServant', verbose_name='authority')),
                ('government_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government_structures.GovernmentStructure', verbose_name='government structure')),
                ('public_enterprises', models.ManyToManyField(to='institutions.InstitutionURL', verbose_name='public enterprises')),
                ('public_servants', models.ManyToManyField(related_name='secretaries', to='public_servants.PublicServant', verbose_name='public servants')),
            ],
            options={
                'verbose_name': 'secretary',
                'verbose_name_plural': 'secretaries',
                'permissions': (('view_secretary', 'Can view secretary'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='secretary',
            unique_together=set([('name', 'government_structure')]),
        ),
    ]
