# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20180305_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='iframe',
            field=models.TextField(verbose_name='iframe'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='url',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='url'),
        ),
    ]
