# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionurl',
            name='url',
            field=models.URLField(unique=True, verbose_name='url'),
        ),
    ]
