# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contingencies', '0002_auto_20171221_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contingencyevent',
            options={'ordering': ('-date_time',), 'verbose_name': 'contingency event', 'verbose_name_plural': 'contingency events'},
        ),
        migrations.AlterModelOptions(
            name='contingencyinformation',
            options={'verbose_name': 'contingency information', 'verbose_name_plural': 'contingency informations'},
        ),
    ]
